apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sentinel-forward-data-action
  description: 'A github action that forwards data from a previous action to Sentinel '
  labels:
    license: MIT
  tags:
    - "github-action"
    - "cds-siem"
    - "tools"
spec:
  type: library
  lifecycle: experimental
  owner: group:cds-snc/internal-sre
  domain: site-reliability-engineering
  system: cds-alm
