name: Use Lighthouse CI Github action and send results to Sentinel
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lighthouse-ci-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lighthouse CI Action 
        id: LHCIAction 
        uses: treosh/lighthouse-ci-action@v9 
        with:
         urls: |
          https://secret.cdssandbox.xyz/

      - name: Send data to sentinel action
        id: sentinel-data-forward 
        uses: cds-snc/sentinel-forward-data-action@main
        with:
         input_data: '{ "links": ${{steps.LHCIAction.outputs.links}}, "manifest": ${{steps.LHCIAction.outputs.manifest}} }'
         log_type: "TestData_CL"
         log_analytics_workspace_id: ${{ secrets.LOG_ANALYTICS_WORKSPACE_ID }}
         log_analytics_workspace_key: ${{ secrets.LOG_ANALYTICS_WORKSPACE_KEY }}
