name: Use Lighthouse CI Github action and send results to Sentinel
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lighthouse-ci-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lighthouse CI Action
        id: lhci_action
        uses: treosh/lighthouse-ci-action@v9
        with:
         urls: |
          https://secret.cdssandbox.xyz/

      - name: Get json file 
        id: get_json_file 
        run: echo "file_name=$(jq -c '.[].jsonPath' <<< '${{steps.lhci_action.outputs.manifest}}')" >> $GITHUB_OUTPUT

      - name: get direcotry listing
        run: |
          ls '${{steps.lhci_action.outputs.resultsPath}}'

      - name: Send data to sentinel action
        id: sentinel-data-forward
        uses: cds-snc/sentinel-forward-data-action@main
        with:
         file_name: ${{ steps.get_json_file.outputs.file_name }}
         input_data: '{ "links": ${{steps.lhci_action.outputs.links}}, "manifest": ${{steps.lhci_action.outputs.manifest}} }'
         log_type: "TestData_CL"
         log_analytics_workspace_id: ${{ secrets.LOG_ANALYTICS_WORKSPACE_ID }}
         log_analytics_workspace_key: ${{ secrets.LOG_ANALYTICS_WORKSPACE_KEY }}
