name: Forward github action data to Sentinel
on:
  push:
    branches:
      - sentinel_data_forwarder 
  pull_request:
    branches:
      - sentinel_data_forwarder 

jobs:
  test-send-data-to-sentinel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Self test
        id: selftest
        uses: ./
        with:
         file_name: ${{ github.event.inputs.file_name }} 
         input_data: $ {{github.event.inputs.input_data }} 
         log-analytics-workspace-id: ${{ secrets.LOG_ANALYTICS_WORKSPACE_ID }}
         log-analytics-workspace-key: ${{ secrets.LOG_ANALYTICS_WORKSPACE_KEY }} 
