name: Test forward github action data to Sentinel
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate-data-from-another-action:
    runs-on: ubuntu-latest
    outputs:
      file_name:   ${{ steps.step1.outputs.file_name}}
      output_data: ${{ steps.step2.outputs.input_data}}
      log_type:    ${{ steps.step3.outputs.log_type}}
    steps:
      - id: step1
        run: echo "file_name=data/test.txt" >> $GITHUB_OUTPUT
      - id: step2
        run: echo "input_data=Sample output that is to be sent to Sentinel" >> $GITHUB_OUTPUT
      - id: step3
        run: echo "log_type=TestGithubAction_CL" >> $GITHUB_OUTPUT

  local-send-data-to-sentinel:
    runs-on: ubuntu-latest
    needs: generate-data-from-another-action
    steps:
      - uses: actions/checkout@v2
      - name: Test chained actions 
        id: selftest
        uses: ./
        with:
         file_name: ${{ needs.generate-data-from-another-action.outputs.file_name }}
         input_data: ${{ needs.generate-data-from-another-action.outputs.output_data }}
         log_type: ${{ needs.generate-data-from-another-action.outputs.log_type}}
         log_analytics_workspace_id: ${{ secrets.LOG_ANALYTICS_WORKSPACE_ID }}
         log_analytics_workspace_key: ${{ secrets.LOG_ANALYTICS_WORKSPACE_KEY }}
